### ISSUE TITLE
Suggestion: use libmenu-cache (EDIT: only 'Generic Name' outstanding)

### ISSUE THREAD

**Issue by Vladimir-csp** [johanmalm/jgmenu#10] opened 2016-10-17 02:15 UTC
libmenu-cache is a set of libraries capable of generating and caching XDG menus. It has few dependencies (libc6, libfm-extra4, libglib2) and supports everything needed, including menu prefixes, proper XDG dirs, menu structure, l10n.

**Comment by johanmalm** [comment] 2016-10-24 21:00
Hi Vladimir. Thanks for the feedback. "libmenu-cache" was one of the options I considered before stubbornly deciding to write  jgmenu-parse-xdg.c from scratch. Have you had a play with jgmenu-parse-xdg? It's pretty small and simple, but does respect xdg dirs+prefixes.

Happy to re-consider. Any thoughts on how to implement?

**Comment by Vladimir-csp** [comment] 2016-11-06 06:05
jgmenu-parse-xdg ingores l10n and separators.

libmenu-cache has roughly similar output file format usable for piping. If started in the right environment, it just dumps everything needed.

**Comment by johanmalm** [comment] 2016-11-08 06:13
I've had a play and got it parsing. Shouldn't be too hard to turn the output into something jgmenu-friendly.

I'm refactoring jgmenu.c at the minute, but will spend some on menu-cache after that.

**Comment by johanmalm** [comment] 2017-05-09 23:58
I've pushed a simple version. You can try it with lx-run.sh

**Comment by Vladimir-csp** [comment] 2017-05-10 12:06
Thanks, I've tested it with LXQt menus.

Issues:
XDG_MENU_PREFIX values are expected to end with `-`, i.e: `lxqt-`
Ordering and hierarchy of items seem to be wrong. Some entries that should be in submenus are flattened into root menu. Some items that should explicitly be in the root menu are not there ("Lock screen", "Заблокировать экран").
L10n is not applied to folder names.
No separators.

Comparison between openbox-menu (libmenu-cache frontend) and jgmenu:
![scr1](https://cloud.githubusercontent.com/assets/4061903/25897546/fcb2a0ce-3590-11e7-859b-9094dba192bb.png)
![scr2](https://cloud.githubusercontent.com/assets/4061903/25897547/fcb302bc-3590-11e7-8c77-0c61d1ed828f.png)

**Comment by johanmalm** [comment] 2017-05-10 13:05
That's great feedback Thanks.
I'll try to straighten it out a bit.

**Comment by johanmalm** [comment] 2017-05-11 20:16
I have had a go at sorting the menu "nesting", but have limited ability to test as I'm not on my normal machine. I tried to install lxqt-panel so that I could compare what it looks like, but there was some library missing so I gave up.
I downloaded lxqt-applications.menu and have attached a screen shot.
I tried manually editing it and as far as I can tell, nested menus work.
Separators work too (based on my testing), but I haven't got my head around all the XDG menu spec subtleties. 
I'm grateful for any feedback you can give me in terms of how it looks on your screen until I can test it more thoroughly myself.

![Uploading 2017-05-11--1494531503_1024x600_scrot.png…]()

I've also sorted the XDG_MENU_PREFIX hyphen. Thanks for spotting that.

I'm not sure what the issue is with l10n on folders. Does it work on applications for you?

For some reason it won't parse xfce-applications.menu, but I think that's a problem with libmenu-cache

**Comment by johanmalm** [comment] 2017-05-11 20:19
![2017-05-11--1494531503_1024x600_scrot](https://cloud.githubusercontent.com/assets/6955353/25970156/86c9c45a-368f-11e7-9895-5e1f8c0f4655.png)

**Comment by johanmalm** [comment] 2017-05-11 20:32
Regarding internationalisation, I have had a quick read on
[https://developer.gnome.org/glib/stable/glib-I18N.html](https://developer.gnome.org/glib/stable/glib-I18N.html)
and added #include <glib/gi18n.h>
Does that make a difference. Sorry for not being able to test this myself.

**Comment by Vladimir-csp** [comment] 2017-05-11 20:47
Hierarchy looks good.
Capricious wine entries with custom paths work.

Folders are still shown unlocalized. But localization is present in jgmenu-parse-lx:
```
$ ./jgmenu-parse-lx
Accessories,^checkout(Стандартные),applications-utilities
wine-wine,^checkout(Wine),wine
Multimedia,^checkout(Аудио и видео),applications-multimedia
Graphics,^checkout(Графика),applications-graphics
Games,^checkout(Игры),applications-games
Internet,^checkout(Интернет),applications-internet
Education,^checkout(Образовательные),applications-accessories
Office,^checkout(Офис),applications-office
Development,^checkout(Программирование),applications-development
System,^checkout(Системные),applications-system
Universal Access,^checkout(Специальные возможности),preferences-desktop-accessibility
Other,^checkout(Прочие),applications-other
^sep()
Preferences,^checkout(Параметры),preferences-desktop
Administration,^checkout(Администрирование),preferences-system
^sep()
Sakura,sakura,terminal-tango
SpaceFM,spacefm %F,spacefm
Accessories,^tag(Стандартные)
compton,compton,compton
DB Browser for SQLite,sqlitebrowser %f,sqlitebrowser
Font Manager,font-manager %u,preferences-desktop-font
Font Viewer,/usr/lib/x86_64-linux-gnu/font-manager/font-viewer %u,preferences-desktop-font
FoxtrotGPS,foxtrotgps,foxtrotgps
...
```
Also, submenus lack 'back' entries

side note: how does jgmenu read tint2 config for themes? in my case it sets  ` - color_menu_bg    = #000000 00`, but my tint2 theme does not have such background anywhere.

**Comment by Vladimir-csp** [comment] 2017-05-11 20:50
xfce menu seems to be broken by itself. Perhaps an outdated syntax.

**Comment by johanmalm** [comment] 2017-05-12 01:37
It was as simple of swap of the "name" and "id". Your message helped me see it, so thanks. I've installed another language so I can check it and it works fine for me. I've pushed a fix.

Adding "Back" in English is a one-liner. To do it with internationalization support takes a bit more work. @o9000 did it in pmenu, so I might try to replicate that :)

For completeness, you can "go back" using backspace, left-arrow or by right clicking. I guess the latter is a bit non-intuitive, so I thought I'd mention it.

t2conf.c does the following with your tint2rc:
  - Finds "panel_background_id" (let's call it "n").
  - Finds the nth "background section" (a background section is started by the keyword "rounded".) In the nth background section it finds "background_color" and uses that value.

Do shout if there is something wrong with the tint2rc parsing. t2conf.c is fairly new - and no doubt has things missing :-)

**Comment by Vladimir-csp** [comment] 2017-05-12 04:18
OK, now l10n is working.
Can you please make an item format selector? To choose which data to show in menu items, like:
`Name - GenericName`, `GenericName: Name`, `Name`, `GenericName`

**Comment by Vladimir-csp** [comment] 2017-05-12 04:36
> Adding "Back" in English is a one-liner. To do it with internationalization support takes a bit more work. @o9000 did it in pmenu, so I might try to replicate that :)

You can make it symbolic.

**Comment by johanmalm** [comment] 2017-05-14 14:43
I've added "Back" (with localization support).

Happy to make it symbolic too as an option (similar to the "arrow_string"). Do say if you want this as it wouldn't be hard to implement.

A "name_format" type config option would be nice. I will do that in jgmenu.c rather than be lx-specific.  Could I just check that I've understood correctly.
For example, if we take /usr/share/applications/desktop-directories/xfce-accessories.directory and use "de..." for LANG, would "Name" be "Zubehör" (i.e. Name[de]) and "GenericName" be "Accessories" (i.e. Name)

**Comment by Vladimir-csp** [comment] 2017-05-14 15:03
I've suggested symbolic "Back" as a way to skip l10n. So if that isn't the issue now, then I don't really care

There are no GenericName fields in desktop-directories (and it would be pointless), only in desktop entries.
```
grep '^GenericName=\|^Name=' /usr/share/applications/*.desktop
```
Obviously, subroutine which would compose item string should be smart enough to skip any conjunctions if either of Name or GenericName is missing, or if both strings match each other, avoiding things like these:
`: Eboard` (eboard.desktop is missing GenericName)
`Reboot - Reboot` (lxqt-reboot.desktop has 'Reboot' string in both Name and GenericName)

**Comment by johanmalm** [comment] 2017-05-14 16:52
Re: Symbolic "Back" - Okay no worries. I guessed that was the case, but didn't want to dismiss it.

Re GenericName - Sorry, I misunderstood. I should have looked a bit harder.
menu-cache.h doesn't have a menu_cache_item_get_generic_name(), but I could parse all the .desktop files and get that value that way.

**Comment by Vladimir-csp** [comment] 2017-05-14 16:56
libmenu-cache has generic name at least in cache output, according to ilbmenu-cache-bin package readme (/usr/share/doc/libmenu-cache-dev/README in debian), so it should have some way to read it.

**Comment by johanmalm** [comment] 2017-05-15 20:50
I've had a look at their github repo. There is a commit a month ago that addresses the issue, so we should see it in future versions.
[https://github.com/lxde/menu-cache/commit/6b88b618792f2d5b2d494e6a383faac32a2ff840](https://github.com/lxde/menu-cache/commit/6b88b618792f2d5b2d494e6a383faac32a2ff840)

I don't think that there is a sensible way of getting the generic_name variable at the moment as the struct is hidden in the C file. I guess we could work out the offset, and get it that way but it's not particularly clean and might break.

**Comment by Vladimir-csp** [comment] 2017-11-22 18:16
menu-cache had an update recently, might be worth investigating.

**Comment by johanmalm** [comment] 2017-11-24 22:04
Thanks for the note. I'll have a play.
The best solution might be to make lx optional in the Makefile, so that we don't break the package on those systems that upgrade packages slowly.

**Comment by johanmalm** [comment] 2018-01-19 22:16
Implemented. Any feedback welcome.

**Comment by Vladimir-csp** [comment] 2018-01-20 07:48
Great!
Would you also add a config option?
And brackets around GenericName are hardcoded, this limits format a bit. I think, this can be made a bit more flexible: set format literally `%n (%g)`, then if both strings are present in the end result, use full format. If only one string is present, use just that string without format.

**Comment by johanmalm** [comment] 2018-01-20 12:36
Good idea. Will do.

**Comment by johanmalm** [comment] 2018-01-20 14:20
That's two commits done (forgot to tag the first one to issue #10)
Your feedback implemented, except that I've ignored the case where there is no "name" as I think it's unlikely. However, do say if you think that is useful - it would be easy to implement.

**Comment by Vladimir-csp** [comment] 2018-01-21 17:08
It works great.
Name is mandatory by the spec, so I guess no further action is needed.

**Comment by johanmalm** [comment] 2018-01-21 21:28
Excellent. I'll close this issue and will try to get on to some of the others.

**Closed by johanmalm** 2018-01-21 21:28 UTC
Labels: enhancement
